language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ammartinezdomingo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ammartinezdomingo/react-test npm test

after_success:
  - docker build -t ammartinezdomingo/multi-client ./client
  - docker build -t ammartinezdomingo/multi-nginx ./nginx
  - docker build -t ammartinezdomingo/multi-server ./server
  - docker build -t ammartinezdomingo/multi-worker ./worker
  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push ammartinezdomingo/multi-client
  - docker push ammartinezdomingo/multi-nginx
  - docker push ammartinezdomingo/multi-server
  - docker push ammartinezdomingo/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-444466521235"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
