language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ammartinezdomingo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ammartinezdomingo/react-test npm test

after_success:
  - docker build -t ammartinezdomingo/multi-client ./client
  - docker build -t ammartinezdomingo/multi-nginx ./nginx
  - docker build -t ammartinezdomingo/multi-server ./server
  - docker build -t ammartinezdomingo/multi-worker ./worker
