name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{secrets.DOCKER_ID}} -p ${{secrets.DOCKER_PASSWORD }}
      - run: docker build -t build -t ammartinezdomingo/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ammartinezdomingo/react-test npm test

      - run: docker build -t ammartinezdomingo/multi-client ./client
      - run: docker build -t ammartinezdomingo/multi-nginx ./nginx
      - run: docker build -t ammartinezdomingo/multi-server ./server
      - run: docker build -t ammartinezdomingo/multi-worker ./worker

      - run: docker push ammartinezdomingo/multi-client
      - run: docker push ammartinezdomingo/multi-nginx
      - run: docker push ammartinezdomingo/multi-server
      - run: docker push ammartinezdomingo/multi-worker
